generate:
	protoc -I ./api --go_out=gen/analytics --go_opt paths=source_relative --go-grpc_out=gen/analytics --go-grpc_opt paths=source_relative --grpc-gateway_out=gen/analytics --grpc-gateway_opt paths=source_relative api/analytics.proto
