generate:
	protoc -I ./api --go_out=gen/auth --go_opt paths=source_relative --go-grpc_out=gen/auth --go-grpc_opt paths=source_relative --grpc-gateway_out=gen/auth --grpc-gateway_opt paths=source_relative api/auth.proto
