generate:
	protoc -I ./api --go_out=gen/billing --go_opt paths=source_relative --go-grpc_out=gen/billing --go-grpc_opt paths=source_relative --grpc-gateway_out=gen/billing --grpc-gateway_opt paths=source_relative api/billing.proto
