// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: user/user_updated/user_updated.proto

package user_updated

import (
	meta "github.com/ilyatos/aac-task-tracker/schema_registry/pkg/meta"
	user "github.com/ilyatos/aac-task-tracker/schema_registry/pkg/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *meta.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*UserUpdated_V1
	Payload isUserUpdated_Payload `protobuf_oneof:"payload"`
}

func (x *UserUpdated) Reset() {
	*x = UserUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_updated_user_updated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdated) ProtoMessage() {}

func (x *UserUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_updated_user_updated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdated.ProtoReflect.Descriptor instead.
func (*UserUpdated) Descriptor() ([]byte, []int) {
	return file_user_user_updated_user_updated_proto_rawDescGZIP(), []int{0}
}

func (x *UserUpdated) GetHeader() *meta.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (m *UserUpdated) GetPayload() isUserUpdated_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *UserUpdated) GetV1() *V1 {
	if x, ok := x.GetPayload().(*UserUpdated_V1); ok {
		return x.V1
	}
	return nil
}

type isUserUpdated_Payload interface {
	isUserUpdated_Payload()
}

type UserUpdated_V1 struct {
	V1 *V1 `protobuf:"bytes,2,opt,name=v1,proto3,oneof"`
}

func (*UserUpdated_V1) isUserUpdated_Payload() {}

type V1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicId string    `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Name     string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email    string    `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role     user.Role `protobuf:"varint,4,opt,name=role,proto3,enum=user.Role" json:"role,omitempty"`
}

func (x *V1) Reset() {
	*x = V1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_updated_user_updated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1) ProtoMessage() {}

func (x *V1) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_updated_user_updated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1.ProtoReflect.Descriptor instead.
func (*V1) Descriptor() ([]byte, []int) {
	return file_user_user_updated_user_updated_proto_rawDescGZIP(), []int{1}
}

func (x *V1) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *V1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *V1) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *V1) GetRole() user.Role {
	if x != nil {
		return x.Role
	}
	return user.Role(0)
}

var File_user_user_updated_user_updated_proto protoreflect.FileDescriptor

var file_user_user_updated_user_updated_proto_rawDesc = []byte{
	0x0a, 0x24, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x1a, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x6f,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x22, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x56, 0x31, 0x48, 0x00, 0x52,
	0x02, 0x76, 0x31, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x6b,
	0x0a, 0x02, 0x56, 0x31, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x4b, 0x5a, 0x49, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6c, 0x79, 0x61, 0x74, 0x6f,
	0x73, 0x2f, 0x61, 0x61, 0x63, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_user_updated_user_updated_proto_rawDescOnce sync.Once
	file_user_user_updated_user_updated_proto_rawDescData = file_user_user_updated_user_updated_proto_rawDesc
)

func file_user_user_updated_user_updated_proto_rawDescGZIP() []byte {
	file_user_user_updated_user_updated_proto_rawDescOnce.Do(func() {
		file_user_user_updated_user_updated_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_user_updated_user_updated_proto_rawDescData)
	})
	return file_user_user_updated_user_updated_proto_rawDescData
}

var file_user_user_updated_user_updated_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_user_updated_user_updated_proto_goTypes = []interface{}{
	(*UserUpdated)(nil), // 0: user_updated.UserUpdated
	(*V1)(nil),          // 1: user_updated.V1
	(*meta.Header)(nil), // 2: header.Header
	(user.Role)(0),      // 3: user.Role
}
var file_user_user_updated_user_updated_proto_depIdxs = []int32{
	2, // 0: user_updated.UserUpdated.header:type_name -> header.Header
	1, // 1: user_updated.UserUpdated.v1:type_name -> user_updated.V1
	3, // 2: user_updated.V1.role:type_name -> user.Role
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_user_updated_user_updated_proto_init() }
func file_user_user_updated_user_updated_proto_init() {
	if File_user_user_updated_user_updated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_user_updated_user_updated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_updated_user_updated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_user_user_updated_user_updated_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UserUpdated_V1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_user_updated_user_updated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_updated_user_updated_proto_goTypes,
		DependencyIndexes: file_user_user_updated_user_updated_proto_depIdxs,
		MessageInfos:      file_user_user_updated_user_updated_proto_msgTypes,
	}.Build()
	File_user_user_updated_user_updated_proto = out.File
	file_user_user_updated_user_updated_proto_rawDesc = nil
	file_user_user_updated_user_updated_proto_goTypes = nil
	file_user_user_updated_user_updated_proto_depIdxs = nil
}
