// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: task/task_updated/task_updated.proto

package task_updated

import (
	meta "github.com/ilyatos/aac-task-tracker/schema_registry/pkg/meta"
	task "github.com/ilyatos/aac-task-tracker/schema_registry/pkg/task"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *meta.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*TaskUpdated_V1
	Payload isTaskUpdated_Payload `protobuf_oneof:"payload"`
}

func (x *TaskUpdated) Reset() {
	*x = TaskUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_task_updated_task_updated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdated) ProtoMessage() {}

func (x *TaskUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_updated_task_updated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdated.ProtoReflect.Descriptor instead.
func (*TaskUpdated) Descriptor() ([]byte, []int) {
	return file_task_task_updated_task_updated_proto_rawDescGZIP(), []int{0}
}

func (x *TaskUpdated) GetHeader() *meta.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (m *TaskUpdated) GetPayload() isTaskUpdated_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *TaskUpdated) GetV1() *V1 {
	if x, ok := x.GetPayload().(*TaskUpdated_V1); ok {
		return x.V1
	}
	return nil
}

type isTaskUpdated_Payload interface {
	isTaskUpdated_Payload()
}

type TaskUpdated_V1 struct {
	V1 *V1 `protobuf:"bytes,2,opt,name=v1,proto3,oneof"`
}

func (*TaskUpdated_V1) isTaskUpdated_Payload() {}

type V1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicId     string      `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	UserPublicId string      `protobuf:"bytes,2,opt,name=user_public_id,json=userPublicId,proto3" json:"user_public_id,omitempty"`
	Description  string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status       task.Status `protobuf:"varint,4,opt,name=status,proto3,enum=task.Status" json:"status,omitempty"`
}

func (x *V1) Reset() {
	*x = V1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_task_updated_task_updated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1) ProtoMessage() {}

func (x *V1) ProtoReflect() protoreflect.Message {
	mi := &file_task_task_updated_task_updated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1.ProtoReflect.Descriptor instead.
func (*V1) Descriptor() ([]byte, []int) {
	return file_task_task_updated_task_updated_proto_rawDescGZIP(), []int{1}
}

func (x *V1) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *V1) GetUserPublicId() string {
	if x != nil {
		return x.UserPublicId
	}
	return ""
}

func (x *V1) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *V1) GetStatus() task.Status {
	if x != nil {
		return x.Status
	}
	return task.Status(0)
}

var File_task_task_updated_task_updated_proto protoreflect.FileDescriptor

var file_task_task_updated_task_updated_proto_rawDesc = []byte{
	0x0a, 0x24, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x1a, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x0b, 0x54, 0x61,
	0x73, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x56, 0x31, 0x48,
	0x00, 0x52, 0x02, 0x76, 0x31, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x8f, 0x01, 0x0a, 0x02, 0x56, 0x31, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73,
	0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x69, 0x6c, 0x79, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x61, 0x63, 0x2d, 0x74, 0x61, 0x73,
	0x6b, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x61,
	0x73, 0x6b, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_task_updated_task_updated_proto_rawDescOnce sync.Once
	file_task_task_updated_task_updated_proto_rawDescData = file_task_task_updated_task_updated_proto_rawDesc
)

func file_task_task_updated_task_updated_proto_rawDescGZIP() []byte {
	file_task_task_updated_task_updated_proto_rawDescOnce.Do(func() {
		file_task_task_updated_task_updated_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_task_updated_task_updated_proto_rawDescData)
	})
	return file_task_task_updated_task_updated_proto_rawDescData
}

var file_task_task_updated_task_updated_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_task_task_updated_task_updated_proto_goTypes = []interface{}{
	(*TaskUpdated)(nil), // 0: task_updated.TaskUpdated
	(*V1)(nil),          // 1: task_updated.V1
	(*meta.Header)(nil), // 2: header.Header
	(task.Status)(0),    // 3: task.Status
}
var file_task_task_updated_task_updated_proto_depIdxs = []int32{
	2, // 0: task_updated.TaskUpdated.header:type_name -> header.Header
	1, // 1: task_updated.TaskUpdated.v1:type_name -> task_updated.V1
	3, // 2: task_updated.V1.status:type_name -> task.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_task_task_updated_task_updated_proto_init() }
func file_task_task_updated_task_updated_proto_init() {
	if File_task_task_updated_task_updated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_task_task_updated_task_updated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_task_updated_task_updated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_task_task_updated_task_updated_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TaskUpdated_V1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_task_updated_task_updated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_task_updated_task_updated_proto_goTypes,
		DependencyIndexes: file_task_task_updated_task_updated_proto_depIdxs,
		MessageInfos:      file_task_task_updated_task_updated_proto_msgTypes,
	}.Build()
	File_task_task_updated_task_updated_proto = out.File
	file_task_task_updated_task_updated_proto_rawDesc = nil
	file_task_task_updated_task_updated_proto_goTypes = nil
	file_task_task_updated_task_updated_proto_depIdxs = nil
}
