generate:
	protoc -I ./api --go_out=gen/tracker --go_opt paths=source_relative --go-grpc_out=gen/tracker --go-grpc_opt paths=source_relative --grpc-gateway_out=gen/tracker --grpc-gateway_opt paths=source_relative api/tracker.proto
